### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by Manuel-3**
German translation because I felt like doing it.

This does not include translations for the documentation, since that would require a lot more time than I was intending to spend on this for now.

Check 8b587678dbc520859b2829f066d32477d75fc522 for more clear diff.

### CODE REVIEW

**Comment by LokiTFD** [comment]
Couldn't have left the german translation to me smh.

**Comment by Fnige** [comment]
Why dont you translate the documentation?

**Comment by LokiTFD** [comment]
when i'm back from my vacation yes

**Comment by lexize** [comment]
> Why dont you translate the documentation?

Because no one dont want to make same mistake what i did.
All lang file has 814 strings, and biggest part of it is docs.
I already started translating docs, so i cant just leave this half completed.
Everyone except me dont want to suffer while translating docs with meaning saving.

**Pull request merged**
