### PR TITLE
PlayerAPI:getAvatar, AvatarAPI:setNBT, AvatarAPI:getModels

### PR DESCRIPTION
**Pull request by BlueMoonJune**
Various methods to deal with others' avatars, and an avatar.json field "allowGetAvatar" (true by default)

### CODE REVIEW

**Comment by ChloeSpacedOut** [comment]
I feel that adding a back-door to other people's avatars, _especially_ one that's opt-out rather than opt-in, is a really bad idea. People can already communicate between avatars, so this doesn't even add extra functionality in terms of multi-avatar applications. It's literally just a way to force other avatars to do things. Not great :p

**Comment by ChloeSpacedOut** [comment]
This also 100% wouldn't work well with the trust menu, since it'd execute on your own avatar, and make it harder to trace who sent it. And it'd bypass your trust settings, so you could just crash others and bypass trust settings, or make HUD model parts and cover other's screens. There's like, only bad applications :p

**Comment by GrandpaScout** [comment]
Both of these functions are already possible in base Figura (and they are opt-in too!)
```lua
avatar:store("models", models)
avatar:store("avatar", avatar)
```
image

**Comment by BlueMoonJune** [comment]
> Both of these functions are already possible in base Figura (and they are opt-in too!)
> 
> ```lua
> avatar:store("models", models)
> avatar:store("avatar", avatar)
> ```
> 
> image

oh yeah that 100% works, didnt think about that



> This also 100% wouldn't work well with the trust menu, since it'd execute on your own avatar, and make it harder to trace who sent it. And it'd bypass your trust settings, so you could just crash others and bypass trust settings, or make HUD model parts and cover other's screens. There's like, only bad applications :p

i dont know how it would bypass your trust settings, because you arent executing code on their side. and making the system opt-in instead of opt-out is also very easy, but GS's solution works so this is kinda pointless.

**Pull request closed without merging**
